import fs from 'node:fs';
import path from 'node:path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'node:url';
import { ENV_REGISTRY, getRegistryMap } from './env-registry.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ENV_PATH = path.join(ROOT, '.env');

const CATEGORY_ORDER = ['core', 'groq', 'autoplay', 'signals', 'playback', 'metrics'];
const REGISTRY_MAP = getRegistryMap();

const PRESETS = {
  stable: {
    AUTOPLAY_FAST_LANE_ENABLED: '1',
    AUTOPLAY_STALE_GUARD_ENABLED: '1',
    AUTOPLAY_POLICY_ENABLED: '1',
    AUTOPLAY_RECOVERY_GROQ_ONLY: '1',
    AUTOPLAY_RECOVERY_STREAK_MIN: '2',
    AUTOPLAY_VARIETY_CONTROLLER_ENABLED: '1',
    AUTOPLAY_ALT_VARIANTS_RELAXED: '1',
    AUTOPLAY_PLAYABILITY_CACHE_SHADOW: '1',
    AUTOPLAY_PLAYABILITY_HARD_SKIP_ENABLED: '1',
    METRICS_TXT_ENABLED: '1',
    MUSIC_SIGNALS_ENABLED: '1',
    MUSIC_BRIDGE_ENABLED: '1',
  },
  conservative: {
    AUTOPLAY_FAST_LANE_ENABLED: '0',
    AUTOPLAY_RECOVERY_GROQ_ONLY: '0',
    AUTOPLAY_VARIETY_CONTROLLER_ENABLED: '0',
    AUTOPLAY_ALT_VARIANTS_RELAXED: '0',
    AUTOPLAY_PLAYABILITY_CACHE_SHADOW: '1',
    AUTOPLAY_PLAYABILITY_HARD_SKIP_ENABLED: '1',
    AUTOPLAY_POLICY_ENABLED: '1',
    AUTOPLAY_STALE_GUARD_ENABLED: '1',
    METRICS_TXT_ENABLED: '1',
    MUSIC_SIGNALS_ENABLED: '1',
    MUSIC_BRIDGE_ENABLED: '1',
  },
};

function printHelp() {
  console.log('ENV easy commands:');
  console.log('  npm run env:setup              -> create .env with stable defaults');
  console.log('  npm run env:doctor             -> check .env and print clear fixes');
  console.log('  npm run env:preset:stable      -> apply stable preset');
  console.log('  npm run env:preset:conservative-> apply conservative preset');
  console.log('  node scripts/env-easy.mjs help -> this message');
}

function parseEnvIfExists() {
  if (!fs.existsSync(ENV_PATH)) return {};
  return dotenv.parse(fs.readFileSync(ENV_PATH, 'utf8'));
}

function normalizePresetName(input) {
  return String(input || 'stable').trim().toLowerCase();
}

function buildDefaultValues() {
  const values = {
    DISCORD_TOKEN: 'your_bot_token_here',
    DISCORD_CLIENT_ID: 'your_application_id_here',
    GROQ_API_KEY: '',
  };
  for (const row of ENV_REGISTRY) {
    if (values[row.name] != null) continue;
    if (row.defaultValue == null) continue;
    values[row.name] = String(row.defaultValue);
  }
  return values;
}

function getGroupedRegistry() {
  const grouped = new Map();
  for (const c of CATEGORY_ORDER) grouped.set(c, []);
  for (const row of ENV_REGISTRY) {
    if (!grouped.has(row.category)) grouped.set(row.category, []);
    grouped.get(row.category).push(row);
  }
  return grouped;
}

function writeEnvFile(values) {
  const grouped = getGroupedRegistry();
  const lines = [];
  lines.push('# Generated by scripts/env-easy.mjs');
  lines.push('# Re-run `npm run env:doctor` after edits');
  lines.push('');

  for (const category of CATEGORY_ORDER) {
    const rows = grouped.get(category) || [];
    if (rows.length === 0) continue;
    lines.push(`# [${category}]`);
    for (const row of rows) {
      const v = values[row.name];
      const rendered = v == null ? '' : String(v);
      lines.push(`${row.name}=${rendered}`);
    }
    lines.push('');
  }

  // Keep unknown keys from existing .env at the end.
  const unknownKeys = Object.keys(values)
    .filter((k) => !REGISTRY_MAP.has(k))
    .sort();
  if (unknownKeys.length > 0) {
    lines.push('# [custom]');
    for (const key of unknownKeys) lines.push(`${key}=${values[key] ?? ''}`);
    lines.push('');
  }

  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf8');
}

function setupEnv(presetName) {
  if (fs.existsSync(ENV_PATH)) {
    console.log('.env already exists; nothing changed.');
    console.log('Use `npm run env:preset:stable` or `npm run env:preset:conservative` to update toggles.');
    return;
  }
  const preset = PRESETS[presetName] || PRESETS.stable;
  const values = { ...buildDefaultValues(), ...preset };
  writeEnvFile(values);
  console.log(`.env created with "${presetName}" preset.`);
  console.log('Next step: set DISCORD_TOKEN (and GROQ_API_KEY if using Groq features).');
}

function applyPreset(presetName) {
  const preset = PRESETS[presetName];
  if (!preset) {
    console.log(`Unknown preset: ${presetName}`);
    console.log(`Available presets: ${Object.keys(PRESETS).join(', ')}`);
    process.exitCode = 1;
    return;
  }
  const existing = parseEnvIfExists();
  const base = fs.existsSync(ENV_PATH) ? existing : buildDefaultValues();
  const values = { ...base, ...preset };
  writeEnvFile(values);
  console.log(`Preset "${presetName}" applied to .env`);
}

function validateBySpec(name, value, spec) {
  if (value == null || value === '') {
    if (spec.required) return `${name} is required`;
    return null;
  }
  if (spec.type === 'bool01') {
    if (!/^(0|1|true|false|yes|no)$/i.test(String(value).trim())) {
      return `${name}: use 0/1 (or true/false)`;
    }
    return null;
  }
  if (spec.type === 'int') {
    const n = Number(value);
    if (!Number.isFinite(n) || !Number.isInteger(n)) return `${name}: must be integer`;
    if (spec.min != null && n < spec.min) return `${name}: must be >= ${spec.min}`;
    if (spec.max != null && n > spec.max) return `${name}: must be <= ${spec.max}`;
    return null;
  }
  if (spec.type === 'float') {
    const n = Number(value);
    if (!Number.isFinite(n)) return `${name}: must be number`;
    if (spec.min != null && n < spec.min) return `${name}: must be >= ${spec.min}`;
    if (spec.max != null && n > spec.max) return `${name}: must be <= ${spec.max}`;
    return null;
  }
  if (spec.type === 'url') {
    try {
      new URL(value);
    } catch {
      return `${name}: must be valid URL`;
    }
    return null;
  }
  return null;
}

function isPlaceholder(value) {
  const v = String(value || '').trim().toLowerCase();
  if (!v) return false;
  return v.includes('your_') || v.includes('_here') || v.includes('changeme');
}

function doctorEnv() {
  if (!fs.existsSync(ENV_PATH)) {
    console.log('.env not found.');
    console.log('Run: npm run env:setup');
    process.exitCode = 1;
    return;
  }

  const values = parseEnvIfExists();
  const errors = [];
  const warnings = [];

  for (const row of ENV_REGISTRY) {
    const value = values[row.name];
    const err = validateBySpec(row.name, value, row);
    if (err) errors.push(err);
  }

  if (isPlaceholder(values.DISCORD_TOKEN)) {
    errors.push('DISCORD_TOKEN still has placeholder value');
  }
  if (!values.GROQ_API_KEY || isPlaceholder(values.GROQ_API_KEY)) {
    warnings.push('GROQ_API_KEY is empty -> Groq-based features will be limited');
  }
  if (!values.DISCORD_CLIENT_ID || isPlaceholder(values.DISCORD_CLIENT_ID)) {
    warnings.push('DISCORD_CLIENT_ID is empty -> register-commands can fail');
  }

  const essentials = [
    ['DISCORD_TOKEN', Boolean(values.DISCORD_TOKEN) && !isPlaceholder(values.DISCORD_TOKEN)],
    ['DISCORD_CLIENT_ID', Boolean(values.DISCORD_CLIENT_ID) && !isPlaceholder(values.DISCORD_CLIENT_ID)],
    ['GROQ_API_KEY', Boolean(values.GROQ_API_KEY) && !isPlaceholder(values.GROQ_API_KEY)],
    ['AUTOPLAY_POLICY_ENABLED', values.AUTOPLAY_POLICY_ENABLED !== '0'],
    ['AUTOPLAY_STALE_GUARD_ENABLED', values.AUTOPLAY_STALE_GUARD_ENABLED !== '0'],
    ['AUTOPLAY_PLAYABILITY_HARD_SKIP_ENABLED', values.AUTOPLAY_PLAYABILITY_HARD_SKIP_ENABLED === '1'],
  ];

  console.log('[env doctor] essentials:');
  for (const [key, ok] of essentials) {
    console.log(`  ${ok ? 'OK ' : 'BAD'} ${key}`);
  }

  if (warnings.length > 0) {
    console.log('\n[env doctor] warnings:');
    warnings.forEach((w) => console.log(`  - ${w}`));
  }

  if (errors.length > 0) {
    console.log('\n[env doctor] errors:');
    errors.forEach((e) => console.log(`  - ${e}`));
    console.log('\nFix errors and run `npm run env:doctor` again.');
    process.exitCode = 1;
    return;
  }

  console.log('\n[env doctor] all required checks passed.');
}

function run() {
  const cmd = normalizePresetName(process.argv[2] || 'help');
  if (cmd === 'help' || cmd === '--help' || cmd === '-h') {
    printHelp();
    return;
  }
  if (cmd === 'setup') {
    setupEnv('stable');
    return;
  }
  if (cmd === 'doctor') {
    doctorEnv();
    return;
  }
  if (cmd === 'preset') {
    const presetName = normalizePresetName(process.argv[3]);
    applyPreset(presetName);
    return;
  }
  if (cmd === 'preset-stable') {
    applyPreset('stable');
    return;
  }
  if (cmd === 'preset-conservative') {
    applyPreset('conservative');
    return;
  }

  console.log(`Unknown command: ${cmd}`);
  printHelp();
  process.exitCode = 1;
}

run();
